-- Coachchat-tabel. Ligt nu ook als Supabase-migratie vast (`coach_messages`),
-- dus een verse omgeving krijgt hem vanzelf; dit bestand blijft staan als
-- leesbare bron en om hem met de hand te kunnen draaien.

create table if not exists public.coach_messages (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null check (role in ('user', 'assistant')),
  content text not null check (char_length(content) between 1 and 5000),
  intent text not null default 'question' check (intent in ('question', 'report', 'plan_review')),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists coach_messages_user_created_idx
  on public.coach_messages (user_id, created_at desc);

alter table public.coach_messages enable row level security;

drop policy if exists "coach_messages_select_own" on public.coach_messages;
create policy "coach_messages_select_own"
  on public.coach_messages for select
  to authenticated
  using (auth.uid() = user_id);

drop policy if exists "coach_messages_insert_own" on public.coach_messages;
create policy "coach_messages_insert_own"
  on public.coach_messages for insert
  to authenticated
  with check (auth.uid() = user_id);
